{% set name = "acgc" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/acgc-{{ version }}.tar.gz
  sha256: ab3e6ae45efc1e3ea63bcea246f67a5067844fdab3d8d123d04da0dd6a85844c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.4
    - setuptools >=61.0
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=3.4
    - matplotlib-base
    - matplotlib-inline
    - cartopy
    - numpy
    - scipy
    - pandas
    - netcdf4
    - scikit-learn
    - statsmodels

test:
  imports:
    - acgc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cdholmes/acgc-python
  doc_url: https://cdholmes.github.io/acgc-python
  dev_url: https://github.com/cdholmes/acgc-python
  summary: A collection of data analysis programs used by the Atmospheric Chemistry and Global Change (ACGC) research group
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cdholmes
