{% set name = "acgc" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/acgc-{{ version }}.tar.gz
  sha256: e9e95847e490feb6fdd53c7eff6017f91c952ecc79702046e26592cc5f03c8be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.4
    - setuptools >=61.0
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=3.4
    - matplotlib-base
    - matplotlib-inline
    - cartopy
    - numpy
    - scipy
    - pandas
    - netcdf4
    - scikit-learn
    - statsmodels

test:
  imports:
    - acgc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cdholmes/acgc-python
  summary: A collection of data analysis programs used by the Atmospheric Chemistry and Global Change (ACGC) research group
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cdholmes
